region:
  name: wppdc
  mareas:
    - Franklin County
    - Pittsylvania County
    - Patrick County
    - Henry County
    - Martinsville City
    - Danville City
  region_geo_values:
    - Virginia

paths:
  source_model_dir: outputs/generated_models/statewide_va_clean
  output_model_dir: outputs/generated_models/wppdc
  validation_report: outputs/reports/wppdc_validation.csv
  manifest: metadata/input_manifest_wppdc_full.csv
  geography_file: defs/geo.csv
